#!/usr/bin/env bash

set -e

bootstrap_log "ensuring ~/.ssh exists"
mkdir -p "$HOME/.ssh"
bootstrap_log "writing include config to ~/.ssh/config"
echo "Include $DOTFILES_BASE_PATH/ssh/config" > "$HOME/.ssh/config"

bootstrap_log "done"
