#!/usr/bin/env bash

set -e

bootstrap_log "removing existing ~/.gitconfig and ~/.gitignore"
rm -f "$HOME/.gitconfig"
rm -f "$HOME/.gitignore"

bootstrap_log "linking gitconfig and gitignore"
ln -sf "$DOTFILES_BASE_PATH/git/gitconfig" "$HOME/.gitconfig"
ln -sf "$DOTFILES_BASE_PATH/git/gitignore" "$HOME/.gitignore"

bootstrap_log "done"
