#!/usr/bin/env bash

set -e

git submodule update --init --recursive

export DOTFILES_BASE_PATH="$HOME/dotfiles"
. "$DOTFILES_BASE_PATH/bash/base"

modules=(
    "1password"
    "bash"
    "bat"
    "bin"
    "ghostty"
    "git"
    "macos"
    "readline"
    "ssh"
    "tmux"
)

for module in "${modules[@]}"; do
    bs="$DOTFILES_BASE_PATH/$module/bootstrap"
    [[ -s "$bs" ]] && (. "$bs")
done

