#!/usr/bin/env bash

if [[ "$(uname)" == *Darwin* ]]; then
    bootstrap_log "applying macOS defaults"
    bash "$DOTFILES_BASE_PATH/macos/defaults"
    bootstrap_log "done"
else
    bootstrap_log "non-macOS system detected; skipping"
fi

