set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-ghostty:RGB"

# set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # sensible defaults
set -g @plugin 'azorng/tmux-smooth-scroll'

# keyboard
set -g mouse on
unbind C-b
set -g prefix C-s
bind C-s send-prefix
bind R source-file ~/.config/tmux/tmux.conf \; display-popup -w 17 -h 3 -E 'echo "config reloaded" && sleep 1'

bind \\ split-window -h
bind - split-window -v
bind l run-shell "tmux popup -E -w 95% -h 95% -x C -y C '~/.config/tmux/tmux-select-window.sh'"
bind w new-window
bind r command-prompt -I "#W" "rename-window '%%'"

set -g @plugin 'christoomey/vim-tmux-navigator' # ctrl-h/j/k/l navigation, plus working within neovim
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-Up C-k"
set -g @vim_navigator_mapping_down "C-Down C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding - we use that for creating vertical splits

# copy and paste
# Make tmux copy to system clipboard and allow normal text selection
set -g set-clipboard on
setw -g mode-keys vi
bind c copy-mode
bind Escape copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind -T copy-mode-vi MouseDragEnd1Pane

# appearance
set -g status-right ""
set -g status-left ""
set -g status-right-length 100
set -g status-left-length 100
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=default,fg=white"
set -g status-right '#(~/.config/tmux/tmux-git-status.sh "#{pane_current_path}" "#{pane_current_command}")'
set -g pane-border-style "fg=gray"
set -g pane-active-border-style "fg=cyan"
set -g pane-border-format " #{s|$HOME|~|:pane_current_path} "
set -g pane-border-status top
set -g base-index 1
set -g automatic-rename off
set -g allow-rename off
set-hook -g after-new-window 'rename-window ""'
set-hook -g session-created 'rename-window ""'
set -g window-status-format " #I#{?#{!=:#{window_name},}, #W,} "
set -g window-status-current-format " #I#{?#{!=:#{window_name},}, #W,} "
set -g window-status-style "fg=white"
set -g window-status-current-style "bg=cyan,fg=black"

run '~/.config/tmux/plugins/tpm/tpm'
