#!/usr/bin/env bash

set -e

bootstrap_log "creating ~/.1password directory"
mkdir -p "$HOME/.1password"

if [[ "$(uname)" == *Darwin* ]]; then
    if [[ -d "$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password" ]]; then
        bootstrap_log "symlinking 1Password agent socket"
        ln -sf "$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock" "$HOME/.1password/agent.sock"
    else
        bootstrap_log "1Password container directory not found; skipping agent socket symlink"
    fi

    bootstrap_log "linking LaunchAgent plist"
    mkdir -p "$HOME/Library/LaunchAgents"
    ln -sf "$DOTFILES_BASE_PATH/1password/com.1password.SSH_AUTH_SOCK.plist" "$HOME/Library/LaunchAgents/com.1password.SSH_AUTH_SOCK.plist"
else
    bootstrap_log "non-macOS system detected; skipping macOS-specific setup"
fi

bootstrap_log "done"
