#!/usr/bin/env bash

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export GIT_CONFIG_GLOBAL="$HOME/.config/git/gitconfig"

export EDITOR='vim'
export VISUAL='vim'
export MANPAGER='less'

[[ $- == *i* ]] || return

. "$XDG_CONFIG_HOME/bash/util"
. "$XDG_CONFIG_HOME/bash/path"
. "$XDG_CONFIG_HOME/bash/envs"
. "$XDG_CONFIG_HOME/bash/funias"
. "$XDG_CONFIG_HOME/bash/complete"
. "$XDG_CONFIG_HOME/bash/shell"

[[ -s "$HOME/.credentials" ]] && . "$HOME/.credentials"

. "$XDG_CONFIG_HOME/bash/prompt"
