#!/usr/bin/env bash

. "$DOTFILES_BASE_PATH/bash/base"

[[ -n "$PS1" ]] || return

. "$DOTFILES_BASE_PATH/bash/path"
. "$DOTFILES_BASE_PATH/bash/envs"
. "$DOTFILES_BASE_PATH/bash/funias"
. "$DOTFILES_BASE_PATH/bash/complete"
. "$DOTFILES_BASE_PATH/bash/shell"

[[ -s "$HOME/.credentials" ]] && . "$HOME/.credentials"

. "$DOTFILES_BASE_PATH/bash/prompt"
