#!/usr/bin/env bash

set -e

bootstrap_log "writing ~/.bashrc shim"
echo ". $DOTFILES_BASE_PATH/bash/bashrc" > "$HOME/.bashrc"
bootstrap_log "ensuring completions directory exists at $XDG_DATA_HOME/bash-completion/completions"
mkdir -p "$XDG_DATA_HOME/bash-completion/completions"
if has fnm; then
    bootstrap_log "generating fnm completions"
    fnm completions --shell bash > "$XDG_DATA_HOME/bash-completion/completions/fnm"
fi
if has docker; then
    bootstrap_log "generating docker completions"
    docker completion bash > "$XDG_DATA_HOME/bash-completion/completions/docker"
fi
if has gh; then
    bootstrap_log "generating gh completions"
    gh completion -s bash > "$XDG_DATA_HOME/bash-completion/completions/gh"
fi

bootstrap_log "done"
