#!/usr/bin/env bash

if command -v batcat >/dev/null 2>&1; then
    alias bat='batcat'
fi

function awsp() {
    export AWS_PROFILE=$(aws configure list-profiles | fzf)
}
alias awsl='aws sso login'
alias lzd='lazydocker'
alias ls='ls --color=auto'
alias l='eza -lh --group-directories-first --icons=auto'
alias ll='l'
alias lg='l --git'
alias la='l -a'
alias lag='l -a --git'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
function gt() {
  tag="$1"
  msg="$2"

  if [[ -z "$msg" ]]; then
    msg="$tag"
  fi

  if [[ -z "$tag" ]]; then
    echo "tag (first argument) missing"
  fi

  git tag -a "$tag" -m "$msg"
}

alias gst='git status'
alias gcm='git commit'
alias gbc='git branch --show-current'
alias lzg='lazygit'

if [[ -d /usr/local/share/chruby ]]; then
    . /usr/local/share/chruby/chruby.sh
fi

if [[ -d /opt/homebrew/opt/chruby ]]; then
    . /opt/homebrew/opt/chruby/share/chruby/chruby.sh
fi

alias x='exit'
