#!/usr/bin/env bash

if has batcat; then
    alias bat='batcat'
fi

if has aws; then
  function awsp() {
      local profile

      profile="$(aws-profiles)" || return
      [[ -n "$profile" ]] || return

      export AWS_PROFILE="$profile"
  }
  alias awsl='aws sso login'
  alias awsme='aws sts get-caller-identity'
  if has docker; then
    alias ecr='aws-ecr-login'
    alias dps='docker ps'
    alias ds='docker stop'
  fi
fi

if has docker; then
  alias ghcr='ghcr-docker-login'
fi

if has lazydocker; then
    alias lzd='lazydocker'
fi
if has eza; then
    alias ls='eza --group-directories-first --icons=auto'
    alias l='eza -lh --group-directories-first --icons=auto'
    alias ll='l'
    alias lg='l --git'
    alias la='l -a'
    alias lag='l -a --git'
    alias lt='eza --tree --level=2 --long --icons --git'
    alias lta='lt -a'
fi
if has fzf; then
    if has bat; then
        alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
    fi
    alias gl='fzf-git-log'
    alias gr='fzf-git-ref'
    alias gco='fzf-git-checkout'
fi

if has rg && has fzf; then
  alias rgf='ripgrep-fzf'
fi

alias gt='git-tag'
alias gst='git status'
alias gss='git-status-summary'
alias gcm='git commit'
alias gbc='git branch --show-current'
alias gacm='git add -A && gcm'
alias gp='git pull'
alias x='exit'
alias exe='chmod +x'
alias cls='clear'
lspath() {
    tr ':' '\n' <<< "$PATH"
}

if has bat; then
    alias cat='bat --paging=never'
fi
