#!/usr/bin/env bash

if [[ -s /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export GOPATH="$HOME/go"
path_prepend /usr/local/go/bin
path_prepend "$GOPATH/bin"
path_prepend "$HOME/.cargo/bin"
# local postgres on macos installed via homebrew
# for local bundle install... Shouldn't really be needed, I hate macos
path_prepend "/opt/homebrew/opt/libpq/bin"
path_prepend "$HOME/.orbstack/bin"
path_prepend "$HOME/.local/bin"
path_prepend "$DOTFILES_BASE_PATH/bin"

chruby_path=""
[[ -d /usr/local/share/chruby ]] && chruby_path="/usr/local/share/chruby"
[[ -d /opt/homebrew/opt/chruby/share/chruby ]] && chruby_path="/opt/homebrew/opt/chruby/share/chruby"
if [[ -n "$chruby_path" ]]; then
    . "$chruby_path/chruby.sh"
    . "$chruby_path/auto.sh"
fi

if has fnm; then
    eval "$(fnm env --use-on-cd --version-file-strategy=recursive --shell bash)"
fi
export PATH
