#!/usr/bin/env bash

if has fzf; then
    eval "$(fzf --bash)"
fi

export HISTCONTROL="ignorespace:ignoredups:erasedups"
export HISTSIZE=5000
export HISTFILESIZE=5000
export HISTIGNORE="ls:ll:l:pwd:clear:history"
export HISTTIMEFORMAT="%F %T "

if has bat; then
    export PAGER='bat'
fi

# Support colors in less - mainly for man pages as the pager is usually bat.
# bat syntax highlighting is still a bit dodgy for man pages unfortunately.
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;33;44m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[4;1;32m'
export LESS_TERMCAP_mr=$'\e[7m'
export LESS_TERMCAP_mh=$'\e[2m'
export LESS_TERMCAP_ZN=$'\e[74m'
export LESS_TERMCAP_ZV=$'\e[75m'
export LESS_TERMCAP_ZO=$'\e[73m'
export LESS_TERMCAP_ZW=$'\e[75m'

shopt -s histappend
shopt -s cdspell
shopt -s checkwinsize
shopt -s extglob
shopt -s autocd   2>/dev/null || true
shopt -s dirspell 2>/dev/null || true
shopt -s cmdhist
shopt -s lithist
shopt -s globstar
shopt -s checkjobs
shopt -s histverify
shopt -s no_empty_cmd_completion


set -o noclobber

