#!/usr/bin/env bash

if command -v fzf >/dev/null 2>&1; then
    eval "$(fzf --bash)"
fi

HISTCONTROL="ignorespace:erasedups"
HISTSIZE=5000
HISTFILESIZE=5000

export EDITOR='vim'
export VISUAL='vim'
# TODO: LSCOLORS, GREP_COLOR, MANPAGER, PAGER, TZ, VISUAL

shopt -s histappend
shopt -s cdspell
shopt -s checkwinsize
shopt -s extglob
shopt -s autocd   2>/dev/null || true
shopt -s dirspell 2>/dev/null || true
